name: example
description: Create beautiful forms with flutter example.
version: 0.0.1
author: Alejandro Rodríguez Angulo <alerodriguezangulo@gmail.com>
repository: https://github.com/alerodang/beautiful_forms

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  beautiful_forms: 0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/logo.png