name: beautiful_forms
description: Create beautiful forms with flutter example.
version: 0.0.2


environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  basic_utils: ^5.7.0
  provider: ^6.1.2
  url_launcher: ^6.3.1
  http: ^1.2.2
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_logo.png
    - assets/images/restaurant_logo.png