name: beautiful_forms
description: Create beautiful forms with flutter example.
version: 0.0.2
author: Alejandro Rodríguez Angulo
homepage:


environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.0
  google_fonts: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.5.1
  build_runner: ^1.0.0

flutter:
  assets:
    - assets/images/logo.png