name: beautiful_forms
description: Create beautiful forms with flutter example.
version: 0.0.2
author: Alejandro Rodríguez Angulo
homepage:


environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.1
  basic_utils: ^1.2.0
  provider: ^4.3.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png